export const youtubeVideos: string[] = [
  'https://www.youtube.com/watch?v=JW5q4w0DDwA',
  '10-Minute Full Body Workout',
  'Easy Breakfast Recipes for Busy Mornings',
  'Productivity Tips for Remote Work',
  'Mindfulness Techniques for Beginners',
  'Healthy Morning Routine Habits',
  'Quick Yoga Flow for Energy',
  'Best Coffee Brewing Methods',
  'Morning Motivation Speech',
  '5-Minute Stretching Exercises',
  'Green Smoothie Recipe Guide',
  'Morning Journal Prompts',
  'Breathing Exercises for Stress Relief',
  'Morning News Digest',
  'Quick Breakfast Meal Prep',
  'Sunrise Time-Lapse Compilation',
  'Morning Affirmations for Success',
  'Wake Up Yoga Sequence',
  'Healthy Morning Habits to Start Today',
  'Morning Piano Music for Focus',
  'Quick Morning Skincare Routine',
  'Morning Walk Nature Sounds',
  '5-Minute Morning Meditation',
  'Energizing Morning Playlist',
  'Morning Reading Recommendations',
  'Quick Morning Stretch Routine',
  'Morning Productivity Hacks',
  'Peaceful Morning Nature Scenes',
  'Morning Mental Health Tips',
  'Start Your Day Right Motivation',
];

export const tiktokVideos: string[] = [
  'https://www.youtube.com/watch?v=JW5q4w0DDwA',
  '10-Minute Full Body Workout',
  'Easy Breakfast Recipes for Busy Mornings',
  'Productivity Tips for Remote Work',
  'Mindfulness Techniques for Beginners',
  'Healthy Morning Routine Habits',
  'Quick Yoga Flow for Energy',
  'Best Coffee Brewing Methods',
  'Morning Motivation Speech',
  '5-Minute Stretching Exercises',
  'Green Smoothie Recipe Guide',
  'Morning Journal Prompts',
  'Breathing Exercises for Stress Relief',
  'Morning News Digest',
  'Quick Breakfast Meal Prep',
  'Sunrise Time-Lapse Compilation',
  'Morning Affirmations for Success',
  'Wake Up Yoga Sequence',
  'Healthy Morning Habits to Start Today',
  'Morning Piano Music for Focus',
  'Quick Morning Skincare Routine',
  'Morning Walk Nature Sounds',
  '5-Minute Morning Meditation',
  'Energizing Morning Playlist',
  'Morning Reading Recommendations',
  'Quick Morning Stretch Routine',
  'Morning Productivity Hacks',
  'Peaceful Morning Nature Scenes',
  'Morning Mental Health Tips',
  'Start Your Day Right Motivation',
];

export const instaVideos: string[] = [
  'https://www.youtube.com/watch?v=JW5q4w0DDwA',
  '10-Minute Full Body Workout',
  'Easy Breakfast Recipes for Busy Mornings',
  'Productivity Tips for Remote Work',
  'Mindfulness Techniques for Beginners',
  'Healthy Morning Routine Habits',
  'Quick Yoga Flow for Energy',
  'Best Coffee Brewing Methods',
  'Morning Motivation Speech',
  '5-Minute Stretching Exercises',
  'Green Smoothie Recipe Guide',
  'Morning Journal Prompts',
  'Breathing Exercises for Stress Relief',
  'Morning News Digest',
  'Quick Breakfast Meal Prep',
  'Sunrise Time-Lapse Compilation',
  'Morning Affirmations for Success',
  'Wake Up Yoga Sequence',
  'Healthy Morning Habits to Start Today',
  'Morning Piano Music for Focus',
  'Quick Morning Skincare Routine',
  'Morning Walk Nature Sounds',
  '5-Minute Morning Meditation',
  'Energizing Morning Playlist',
  'Morning Reading Recommendations',
  'Quick Morning Stretch Routine',
  'Morning Productivity Hacks',
  'Peaceful Morning Nature Scenes',
  'Morning Mental Health Tips',
  'Start Your Day Right Motivation',
];

export const flowerList: string[] = [
  'Jasmine',
  'Tulips',
  'BabysBreath',
  'Daffodils',
  'Lily',
  'Daisy',
  'Orchid',
  'Buttercup',
  'Hyacinths',
  'Lilies',
  'Lavender',
  'Cosmos',
  'Mums',
  'Roses',
  'Pansies',
  'Bellflower',
  'ScorpionGrass',
  'Hydrangea',
  'Frangipani',
  'Crayon',
  'Murray',
  'Penguin',
  'Windflowers',
  'Jasmine',
  'Tulips',
  'BabysBreath',
  'Daffodils',
  'Lily',
  'Daisy',
  'Orchid',
];

export const flowerFacts: string[] = [
  'Jasmine flowers are used in many traditional perfumes and have been used in aromatherapy for centuries.',
  'Tulips were once more valuable than gold in Holland during the 1600s "tulip mania" period.',
  "Baby's Breath is traditionally used in bridal bouquets and symbolizes everlasting love.",
  'Daffodils contain toxic crystals in their stems that can be harmful to other flowers in a vase.',
  'Some lily species can grow up to 8 feet tall in the wild.',
  'Daisies are actually two flowers in one - the white petals and the center yellow disc.',
  'There are over 25,000 different species of orchids in the world.',
  'Buttercups reflect light from their petals, creating the yellow glow under your chin.',
  'Hyacinths were named after a Greek myth about Apollo and the youth Hyakinthos.',
  'Easter lilies can be fatal to cats if ingested.',
  'Lavender has been used as a sleep aid and antiseptic for over 2,500 years.',
  'Cosmos flowers are named after the Greek word for "harmony" or "ordered universe."',
  'Chrysanthemums (Mums) are the official flower of several Asian cities.',
  'Roses are related to apples, raspberries, cherries, and plums.',
  'Pansies can bloom in the snow and are edible flowers.',
  'Bellflowers get their name from their bell-shaped blooms.',
  'Scorpion Grass is the original name for Forget-Me-Nots.',
  'Hydrangea flower colors change based on soil pH levels.',
  'Frangipani flowers can bloom up to 200 days a year.',
  'Crayon flowers are commonly used in traditional medicine.',
  'Murray River Wattle is native to Australia.',
  'Penguin flowers get their name from their black and white appearance.',
  'Windflowers close their petals when wind speeds increase.',
  'Jasmine flowers open at night and close during the day.',
  'Tulips continue to grow after being cut.',
  "Baby's Breath can survive in very dry conditions.",
  'Daffodils have been used in medicine to create treatments for Alzheimer`s.',
  'Water lilies can support the weight of a small child.',
  'The daisy family is one of the largest families of flowering plants.',
  'Some orchids can live up to 100 years.',
];

export const songList: string[] = [
  'We`ll Never Have Sex',
  'Heart of Gold',
  'Amoeba',
  'touch tank',
  'Everyone lve Never Met',
  'The Birthday Party',
  'Me and You`re There',
  'Undo',
  'House on Fire',
  'just like heaven',
  'Sunsetz',
  'The Cold War',
  '1 step forward, 3 steps back',
  'Curls',
  'Apocalypse',
  'Sweet',
  '1/2',
  'The Seed',
  'I Wanna Be Yours',
  'Fallingforyou',
  'Affection',
  'All I Need To Hear',
  'Call It Dreaming',
  'Beach Baby',
  'Flightless Bird, American Mouth',
  'Sea of Love',
  'Meet Me In The Woods',
  'K.',
  'The Night We Met',
  'Walls',
];

export const albumArt: string[] = [
  require('@assets/songArt/1.jpg'),
  require('@assets/songArt/2.jpg'),
  require('@assets/songArt/3.jpg'),
  require('@assets/songArt/4.jpg'),
  require('@assets/songArt/5.jpg'),
  require('@assets/songArt/6.jpg'),
  require('@assets/songArt/7.jpg'),
  require('@assets/songArt/8.jpg'),
  require('@assets/songArt/9.jpg'),
  require('@assets/songArt/10.jpg'),
  require('@assets/songArt/11.jpg'),
  require('@assets/songArt/12.jpg'),
  require('@assets/songArt/13.jpg'),
  require('@assets/songArt/14.jpg'),
  require('@assets/songArt/15.jpg'),
  require('@assets/songArt/16.jpg'),
  require('@assets/songArt/17.jpg'),
  require('@assets/songArt/18.jpg'),
  require('@assets/songArt/19.jpg'),
  require('@assets/songArt/20.jpg'),
  require('@assets/songArt/21.jpg'),
  require('@assets/songArt/22.jpg'),
  require('@assets/songArt/23.jpg'),
  require('@assets/songArt/24.jpg'),
  require('@assets/songArt/25.jpg'),
  require('@assets/songArt/26.jpg'),
  require('@assets/songArt/27.jpg'),
  require('@assets/songArt/28.jpg'),
  require('@assets/songArt/29.jpg'),
  require('@assets/songArt/30.jpg'),
];

export const spotifyLinks: string[] = [
  'https://open.spotify.com/track/4zXuYQNDmw3dlauyc8q3Kd?si=3a357559fad44e04',
  'https://open.spotify.com/track/0hrqmCqa4vafVqafkwpwOm?si=64d518a2fe074896',
  'https://open.spotify.com/track/0HAqq2GcQKyi3s87GuN7jU?si=47079a2cb9f54739',
  'https://open.spotify.com/track/7DrzZN5jaDyE0a0tVuVWnj?si=2afa9c88d3fa41d5',
  'https://open.spotify.com/track/01cuVZlQ0fjxgxy7MwHRru?si=31b4804537954107',
  'https://open.spotify.com/track/1LmYdO6048yzPWcd7IVdhO?si=5b7c51b89120482d',
  'https://open.spotify.com/track/2POA0X4Whsen49Zy0cgIlU?si=5efe5ff03da24407',
  'https://open.spotify.com/track/68HmOLTXM8aXfEWK4wuniu?si=6977281732224204',
  'https://open.spotify.com/track/2J41Pky0lBqORpklPXqfVC?si=1d5b362d629e4041',
  'https://open.spotify.com/track/11xjDJ7i9BLd1AYMedwJQK?si=617252c6cc334465',
  'https://open.spotify.com/track/0SpkyS1Q4MD8GaVcP5YjT4?si=9a5154b968904cc6',
  'https://open.spotify.com/track/2ICSaeC3wMM1Vl6ONWWo42?si=b8fa1f08292c4668',
  'https://open.spotify.com/track/4wcBRRpIfesgcyUtis7PEg?si=48537e98a39d4963',
  'https://open.spotify.com/track/3NLm801woJocONz1NmPJZR?si=00ca0e155ac94440',
  'https://open.spotify.com/track/0yc6Gst2xkRu0eMLeRMGCX?si=f4914e5d75e142f6',
  'https://open.spotify.com/track/6ilc4vQcwMPlvAHFfsTGng?si=377c1f7240ba468b',
  'https://open.spotify.com/track/7oiYel6EJy3uHJzTXNjfwB?si=9382b07943294ad1',
  'https://open.spotify.com/track/3DNsrmjHGtzEqbumrvpFB5?si=e30958dfda1647d7',
  'https://open.spotify.com/track/5XeFesFbtLpXzIVDNQP22n?si=809960ec62924973',
  'https://open.spotify.com/track/4Ol4KmWekMsgeNwGYhskYG?si=7c251d2ad7544fc8',
  'https://open.spotify.com/track/4eVNSHRazoHgfYGv3AYFyZ?si=5df9985da5e04646',
  'https://open.spotify.com/track/42Q00bTTgyQhPE2FVWaoJE?si=4c8782567b32439f',
  'https://open.spotify.com/track/1MxHIIzcTeFnaNsDGY3pfj?si=0c915c86b9d04f3b',
  'https://open.spotify.com/track/2LXtyj95dK56ENS1QLt4IB?si=25b8a2d35cbe4b6b',
  'https://open.spotify.com/track/1fEGtTZjrjJW8eUeewnNJR?si=f820829915ac471b',
  'https://open.spotify.com/track/33kKcOJoyNduHwXhEnga8X?si=5667958b3fad4f1a',
  'https://open.spotify.com/track/54hj06Z7sm7DaHSrGGMAZG?si=6a5f805f73ae4942',
  'https://open.spotify.com/track/1FWsomP9StpCcXNWmJk8Cl?si=07ff9ad3a7be4fa8',
  'https://open.spotify.com/track/3hRV0jL3vUpRrcy398teAU?si=4db89c4aee644503',
  'https://open.spotify.com/track/55OslhCKptoOWToLXZsPLz?si=7870a6b5093d45aa',
];

export const personName: string[] = ['Harlen', 'Lilly', 'Fio'];

export const personQuote: string[] = [
  'I love yuo so so so much I really do ur so lovely and nice to me',
  'Lilly',
  'Fio',
];
